spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: veterinary
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/veterinaria?serverTimezone=America/Bogota
    username: root
    password:
    hikari:
      maximum-pool-size: 1
      pool-name: VeterinaryPool
  jackson:
    default-property-inclusion: NON_ABSENT
    serialization:
      fail-on-empty-beans: false


logging:
  level:
    com.veterinary: DEBUG
